name: release
description: release executables

inputs:
  tag:
    description: check out the tag if not empty
    default: ''
  token:
    description: GitHub token
    required: true

runs:
  using: composite

  steps:
  - uses: actions/checkout@v3
    name: "checkout tag ${{ inputs.tag }}"
    if: "inputs.tag != ''"
    with:
      ref: refs/tags/${{ inputs.tag }}
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
  - name: Set up QEMU for cross-platform image build
    uses: docker/setup-qemu-action@v2
  - name: Set up Go
    uses: actions/setup-go@v2
    with:
      go-version: ~1.19
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v2
    with:
      registry: ghcr.io
      username: pfnet-research
      password: ${{ inputs.token }}
  - name: Run GoReleaser
    uses: goreleaser/goreleaser-action@v3
    with:
      version: v1.11.5
      args: release --rm-dist
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
